substitutions:
  device_name: diningroom-windowshutter
  friendly_name: "Diningroom Window Shutter"
  static_ip: 192.168.1.27

  # Applicable for Curtain Switches
  duration_open: "16" # Actually 15
  duration_close: "15" # Actually 14

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_shutterswitch_wfcs01.yaml
