substitutions:
  device_name: garden-light
  friendly_name: "Garden Light"
  static_ip: 192.168.1.36

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_lightswitch_wfws02.yaml
