substitutions:
  device_name: hallway-light
  friendly_name: "Hallway Light"
  static_ip: 192.168.1.65

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_mini_toggle.yaml
