substitutions:
  device_name: kitchen_light_ceiling
  friendly_name: "Kitchen Light Ceiling"  
  static_ip: 192.168.1.26

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_lightswitch_wfws01.yaml
