substitutions:
  device_name: livingroom_light
  friendly_name: "Livingroom Light"
  static_ip: 192.168.1.69

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_mini_onoff.yaml
