substitutions:
  name: m5stack-atom-echo-104af0
  friendly_name: M5Stack Atom Echo 104af0 2
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: WtxraqE3fmm7j9QipHokeOVQrOCIQxwZk/ULfgYa7KA=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
