substitutions:
  name: m5stack-atom-echo-104a70
  friendly_name: M5Stack Atom Echo 104a70 1
packages:
  # m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
  m5stack.atom-echo-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: nnbrmcBt6IFuQodL2u57nU+9k/XP8PGuqupjao1Guf8=


wifi:
  ssid: !secret WIFI_SSID_1
  password: !secret WIFI_Password_1
