substitutions:
  device_name: main_bathroom_heater
  friendly_name: "Main Bathroom Heater"
  static_ip: 192.168.1.46
  max_duration_on: 60 min # Limit switch ON time

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_heaterswitch_wh100weu.yaml
