substitutions:
  device_name: master_bedroom_left_light
  friendly_name: "Master Bedroom Left Light"
  static_ip: 192.168.1.67

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_mini_toggle.yaml