substitutions:
  device_name: master-bathroom-light
  friendly_name: "Master Bathroom Light"
  static_ip: 192.168.1.23

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_lightswitch_wfws02.yaml