substitutions:
  device_name: roof_right_table_power
  friendly_name: "Roof Right Table Power"
  static_ip: 192.168.1.63

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_basic.yaml
