substitutions:
  device_name: sonoff-mini-4 #livingroom-light
  friendly_name: "Sonoff Mini 4"
  static_ip: 192.168.1.64
  onoff_toggle: "toggle"

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_mini.yaml
